### ISSUE TITLE
Feature: Optionally let the user choose their preferred/local currency

### ISSUE THREAD

**Issue by the-lazy-learner** [JoshuaKGoldberg/tidelift-me-up#23]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Currently, the program only suggests amount in USD, but I feel it might be more convenient to the user to have it show an estimate in their preferred currency.

**Comment by JoshuaKGoldberg** [comment]
Thanks for filing @the-lazy-learner! ❤️ 

We chatted on the Twitch stream today - Tidelift only sends payments in $USD. So in order to do this, we'd have to make a network call to determine exchange rate. And then it'd still be not the same as what Tidelift gives. I'm going to close this as wontfix - but I appreciate you filing!
